apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-uploader
  namespace: file-service-test
spec:
  selector:
    matchLabels:
      app: file-uploader
  template:
    metadata:
      labels:
        app: file-uploader
    spec:
      containers:
      - name: file-uploader
        image: farshinasri/file-uploader:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/uploads
          name: uploads-volume

      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-uploader-service
  namespace: file-service-test
spec:
  type: LoadBalancer
  selector:
    app:  file-uploader
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
