
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-file-uploader
  namespace: file-service-test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/projects/km/uploaded-files